version: '3'
services:

  db:
    image: mongo:7.0.0
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  rabbit:
    image: rabbitmq:3.12.4-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - ${TMP}/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/app/src:z
      - ./video-streaming/videos:/usr/app/videos:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - ${TMP}/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/app/src:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - NODE_ENV=development
    restart: "no"

  recommendations:
    image: recommendations
    build:
      context: ./recommendations
      dockerfile: Dockerfile-dev
    container_name: recommendations
    volumes:
      - ${TMP}/recommendations/npm-cache:/root/.npm:z
      - ./recommendations/src:/usr/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=recommendations
      - NODE_ENV=development
    restart: "no"
